-- 系统自然拼读：短元音 → 首音拼读 → CVC 词族
INSERT INTO theme (id, name, sort_order, is_locked, subject_id)
VALUES (48, '系统自然拼读', 17, 0, 1);

INSERT INTO unit (id, theme_id, name, sort_order, is_locked) VALUES
(103, 48, '短元音与首音', 1, 0),
(104, 48, 'CVC 词族', 2, 0);

INSERT INTO lesson (id, unit_id, name, type, content, sort_order, star_reward) VALUES
(486, 103, '短元音 a', 'PHONICS', '{"type":"PHONICS","letter":"Aa","pronunciation":"eɪ","sound":"æ","tip":"张大嘴巴，发短促的 /æ/ 音。","items":[{"word":"cat","phonetic":"kæt","translation":"小猫","image":"pet/kitten","emoji":"🐱","distractors":["Ee","Ii"]},{"word":"ant","phonetic":"ænt","translation":"蚂蚁","image":"insect/ant","emoji":"🐜","distractors":["Ee","Oo"]},{"word":"map","phonetic":"mæp","translation":"地图","image":"camping/map","emoji":"🗺️","distractors":["Ii","Uu"]}]}', 1, 3),
(487, 103, '短元音 e', 'PHONICS', '{"type":"PHONICS","letter":"Ee","pronunciation":"iː","sound":"e","tip":"嘴角微微向两边，发短促的 /e/ 音。","items":[{"word":"bed","phonetic":"bed","translation":"床","image":"camping/sleeping-bag","emoji":"🛏️","distractors":["Aa","Ii"]},{"word":"hen","phonetic":"hen","translation":"母鸡","image":"paw-patrol/chickaletta","emoji":"🐔","distractors":["Aa","Oo"]},{"word":"pen","phonetic":"pen","translation":"笔","image":"math/pencil-9","emoji":"✏️","distractors":["Ii","Uu"]}]}', 2, 3),
(488, 103, '短元音 i', 'PHONICS', '{"type":"PHONICS","letter":"Ii","pronunciation":"aɪ","sound":"ɪ","tip":"嘴巴放松，快速发 /ɪ/ 音。","items":[{"word":"fish","phonetic":"fɪʃ","translation":"鱼","image":"ocean/clownfish","emoji":"🐟","distractors":["Aa","Ee"]},{"word":"sit","phonetic":"sɪt","translation":"坐下","image":"sports/balance-beam","emoji":"🪑","distractors":["Ee","Oo"]},{"word":"six","phonetic":"sɪks","translation":"数字六","image":"math/number-6","emoji":"6️⃣","distractors":["Aa","Uu"]}]}', 3, 3),
(489, 103, '短元音 o', 'PHONICS', '{"type":"PHONICS","letter":"Oo","pronunciation":"oʊ","sound":"ɒ","tip":"嘴巴张圆，发短促的 /ɒ/ 音。","items":[{"word":"dog","phonetic":"dɒɡ","translation":"小狗","image":"pet/puppy","emoji":"🐶","distractors":["Aa","Ee"]},{"word":"fox","phonetic":"fɒks","translation":"狐狸","image":"story/fox-tiger-1","emoji":"🦊","distractors":["Ii","Uu"]},{"word":"hot","phonetic":"hɒt","translation":"热","image":"energy/geothermal","emoji":"♨️","distractors":["Aa","Ii"]}]}', 4, 3),
(490, 103, '短元音 u', 'PHONICS', '{"type":"PHONICS","letter":"Uu","pronunciation":"juː","sound":"ʌ","tip":"嘴巴自然打开，发短促的 /ʌ/ 音。","items":[{"word":"sun","phonetic":"sʌn","translation":"太阳","image":"energy/solar-power","emoji":"☀️","distractors":["Aa","Oo"]},{"word":"bug","phonetic":"bʌɡ","translation":"小虫","image":"insect/ladybug","emoji":"🐞","distractors":["Ee","Ii"]},{"word":"run","phonetic":"rʌn","translation":"跑步","image":"sports/running","emoji":"🏃","distractors":["Aa","Oo"]}]}', 5, 3),
(491, 103, '听首音找字母', 'PHONICS', '{"type":"PHONICS","tip":"先听单词开头的声音，再找到对应字母。","items":[{"letter":"Mm","pronunciation":"em","sound":"m","tip":"双唇合拢，鼻腔轻轻发声。","word":"map","phonetic":"mæp","translation":"地图","image":"camping/map","emoji":"🗺️","distractors":["Pp","Tt"]},{"letter":"Pp","pronunciation":"piː","sound":"p","tip":"双唇闭合后轻轻送气。","word":"puppy","phonetic":"ˈpʌpi","translation":"小狗","image":"pet/puppy","emoji":"🐶","distractors":["Mm","Tt"]},{"letter":"Tt","pronunciation":"tiː","sound":"t","tip":"舌尖轻触上齿龈后送气。","word":"tomato","phonetic":"təˈmɑːtoʊ","translation":"番茄","image":"plant/tomato","emoji":"🍅","distractors":["Mm","Pp"]}]}', 6, 3),
(492, 104, '-at 词族', 'PHONICS', '{"type":"PHONICS","letter":"-at","pronunciation":"æt","sound":"æt","tip":"先读 /æ/，再接 /t/，合起来读 -at。","items":[{"word":"cat","phonetic":"kæt","translation":"小猫","image":"pet/kitten","emoji":"🐱","distractors":["-an","-it"]},{"word":"hat","phonetic":"hæt","translation":"帽子","image":"words/hard-hat","emoji":"🧢","distractors":["-op","-ug"]},{"word":"mat","phonetic":"mæt","translation":"垫子","image":"sports/balance-beam","emoji":"🟫","distractors":["-an","-en"]}]}', 1, 3),
(493, 104, '-an 词族', 'PHONICS', '{"type":"PHONICS","letter":"-an","pronunciation":"æn","sound":"æn","tip":"先读 /æ/，再接 /n/，合起来读 -an。","items":[{"word":"fan","phonetic":"fæn","translation":"风扇","image":"energy/electric-fan","emoji":"🪭","distractors":["-at","-it"]},{"word":"man","phonetic":"mæn","translation":"男人","image":"career/doctor","emoji":"👨","distractors":["-op","-ug"]},{"word":"van","phonetic":"væn","translation":"厢式车","image":"career/ambulance","emoji":"🚐","distractors":["-at","-en"]}]}', 2, 3),
(494, 104, '-it 词族', 'PHONICS', '{"type":"PHONICS","letter":"-it","pronunciation":"ɪt","sound":"ɪt","tip":"先读 /ɪ/，再接 /t/，合起来读 -it。","items":[{"word":"sit","phonetic":"sɪt","translation":"坐下","image":"sports/balance-beam","emoji":"🪑","distractors":["-at","-op"]},{"word":"fit","phonetic":"fɪt","translation":"健康强壮","image":"sports/running","emoji":"💪","distractors":["-an","-ug"]},{"word":"hit","phonetic":"hɪt","translation":"击打","image":"sports/tennis","emoji":"🎾","distractors":["-op","-en"]}]}', 3, 3),
(495, 104, '-op 词族', 'PHONICS', '{"type":"PHONICS","letter":"-op","pronunciation":"ɒp","sound":"ɒp","tip":"先读 /ɒ/，再接 /p/，合起来读 -op。","items":[{"word":"hop","phonetic":"hɒp","translation":"单脚跳","image":"sports/jump-rope","emoji":"🦘","distractors":["-at","-it"]},{"word":"top","phonetic":"tɒp","translation":"顶部","image":"building/tower","emoji":"🔝","distractors":["-an","-ug"]},{"word":"mop","phonetic":"mɒp","translation":"拖地","image":"pet/cleaning","emoji":"🧹","distractors":["-it","-en"]}]}', 4, 3),
(496, 104, '-ug 词族', 'PHONICS', '{"type":"PHONICS","letter":"-ug","pronunciation":"ʌɡ","sound":"ʌɡ","tip":"先读 /ʌ/，再接 /ɡ/，合起来读 -ug。","items":[{"word":"bug","phonetic":"bʌɡ","translation":"小虫","image":"insect/ladybug","emoji":"🐞","distractors":["-at","-an"]},{"word":"hug","phonetic":"hʌɡ","translation":"拥抱","image":"emotion/hug","emoji":"🤗","distractors":["-it","-op"]}]}', 5, 3),
(497, 104, '-en 词族', 'PHONICS', '{"type":"PHONICS","letter":"-en","pronunciation":"en","sound":"en","tip":"先读 /e/，再接 /n/，合起来读 -en。","items":[{"word":"hen","phonetic":"hen","translation":"母鸡","image":"paw-patrol/chickaletta","emoji":"🐔","distractors":["-at","-an"]},{"word":"pen","phonetic":"pen","translation":"笔","image":"math/pencil-9","emoji":"✏️","distractors":["-it","-op"]},{"word":"ten","phonetic":"ten","translation":"数字十","image":"math/number-10","emoji":"🔟","distractors":["-an","-ug"]}]}', 6, 3);
