-- V83：按人教统编一年级上册（2024 修订版）识字表补齐 256 字。

-- 保留原有 24 字与学习记录；组词、短句和配图为本项目原创或项目内复用。

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·识字一',3,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 1（天地人你）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"天","phonetic":"tiān","exampleWord":"天空","exampleSentence":"天空很蓝。","image":"english-nature/sky","translation":"天空","recognition":true,"sourceSection":"天地人","imageChoice":true},{"word":"地","phonetic":"dì","exampleWord":"地面","exampleSentence":"我把地面扫干净。","image":"hanzi-preschool/ground","translation":"地面","recognition":true,"sourceSection":"天地人","imageChoice":true,"readingNote":"本课读 dì（地面）；教材另学 de（轻轻地）。"},{"word":"人","phonetic":"rén","exampleWord":"人们","exampleSentence":"公园里有人。","image":"hanzi-preschool/person","translation":"人们","recognition":true,"sourceSection":"天地人","imageChoice":true},{"word":"你","exampleWord":"你们","exampleSentence":"你们在一起。","image":"english-family/family","imageChoice":false,"phonetic":"nǐ","translation":"你们","recognition":true,"sourceSection":"天地人"}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 2（我他一二）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"我","exampleWord":"我们","exampleSentence":"我们在一起。","image":"english-family/family","imageChoice":false,"phonetic":"wǒ","translation":"我们","recognition":true,"sourceSection":"天地人"},{"word":"他","exampleWord":"他们","exampleSentence":"他们在一起。","image":"english-family/family","imageChoice":false,"phonetic":"tā","translation":"他们","recognition":true,"sourceSection":"天地人"},{"word":"一","phonetic":"yī","exampleWord":"一颗","exampleSentence":"盘子里有一颗草莓。","image":"hanzi-preschool/count-one","translation":"一颗","recognition":true,"sourceSection":"金木水火土","imageChoice":true},{"word":"二","phonetic":"èr","exampleWord":"数到二","exampleSentence":"看着两只小鸭，我们数到二。","image":"hanzi-preschool/count-two","translation":"数到二","recognition":true,"sourceSection":"金木水火土","imageChoice":true}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 3（三四五口）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"三","phonetic":"sān","exampleWord":"三只","exampleSentence":"草地上有三只小兔。","image":"hanzi-preschool/count-three","translation":"三只","recognition":true,"sourceSection":"金木水火土","imageChoice":true},{"word":"四","phonetic":"sì","exampleWord":"四个","exampleSentence":"桌上有四个苹果。","image":"hanzi-preschool/count-four","translation":"四个","recognition":true,"sourceSection":"金木水火土","imageChoice":true},{"word":"五","phonetic":"wǔ","exampleWord":"五颗","exampleSentence":"盘子里有五颗草莓。","image":"hanzi-preschool/count-five","translation":"五颗","recognition":true,"sourceSection":"金木水火土","imageChoice":true},{"word":"口","phonetic":"kǒu","exampleWord":"口中","exampleSentence":"口中有牙齿。","image":"english-body/mouth","translation":"口中","recognition":true,"sourceSection":"口耳目手足","imageChoice":true}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 4（耳目手足）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"耳","phonetic":"ěr","exampleWord":"耳朵","exampleSentence":"我用耳朵听声音。","image":"english-body/ear","translation":"耳朵","recognition":true,"sourceSection":"口耳目手足","imageChoice":true},{"word":"目","phonetic":"mù","exampleWord":"双目","exampleSentence":"我用双目看花。","image":"english-body/eye","translation":"双目","recognition":true,"sourceSection":"口耳目手足","imageChoice":true},{"word":"手","phonetic":"shǒu","exampleWord":"小手","exampleSentence":"我把小手洗干净。","image":"english-body/hand","translation":"小手","recognition":true,"sourceSection":"口耳目手足","imageChoice":true},{"word":"足","phonetic":"zú","exampleWord":"双足","exampleSentence":"我的双足站在地上。","image":"english-body/foot","translation":"双足","recognition":true,"sourceSection":"口耳目手足","imageChoice":true}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 5（站坐川火）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"站","exampleWord":"站立","exampleSentence":"小朋友站立得很稳。","image":"hanzi-preschool/body","imageChoice":false,"phonetic":"zhàn","translation":"站立","recognition":true,"sourceSection":"口耳目手足"},{"word":"坐","phonetic":"zuò","exampleWord":"坐下","exampleSentence":"我轻轻坐下。","image":"hanzi-preschool/sit","translation":"坐下","recognition":true,"sourceSection":"口耳目手足","imageChoice":true},{"word":"川","exampleWord":"山川","exampleSentence":"山川之间有一条河。","image":"hanzi-pilot/hanzi-shui","imageChoice":false,"phonetic":"chuān","translation":"山川","recognition":true,"sourceSection":"日月山川"},{"word":"火","exampleWord":"火苗","exampleSentence":"火苗很烫，要离远一点。","image":"hanzi-preschool/fire","imageChoice":true,"phonetic":"huǒ","translation":"火苗","recognition":true,"sourceSection":"日月山川"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 6（田禾六七）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"田","phonetic":"tián","exampleWord":"稻田","exampleSentence":"稻田里的禾苗绿了。","image":"hanzi-preschool/field","translation":"稻田","recognition":true,"sourceSection":"日月山川","imageChoice":true},{"word":"禾","phonetic":"hé","exampleWord":"禾苗","exampleSentence":"田里长出了禾苗。","image":"hanzi-preschool/rice-seedling","translation":"禾苗","recognition":true,"sourceSection":"日月山川","imageChoice":true},{"word":"六","phonetic":"liù","exampleWord":"六个","exampleSentence":"桌上有六个积木。","image":"hanzi-preschool/count-six","translation":"六个","recognition":true,"sourceSection":"语文园地一","imageChoice":true},{"word":"七","phonetic":"qī","exampleWord":"七个","exampleSentence":"盒子里有七个球。","image":"hanzi-preschool/count-seven","translation":"七个","recognition":true,"sourceSection":"语文园地一","imageChoice":true}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字一 · 7（八九十）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":1,"items":[{"word":"八","phonetic":"bā","exampleWord":"八个","exampleSentence":"桌上有八个积木。","image":"chinese-pinyin/eight-blocks","translation":"八个","recognition":true,"sourceSection":"语文园地一","imageChoice":true},{"word":"九","phonetic":"jiǔ","exampleWord":"九个","exampleSentence":"盘子里有九个苹果。","image":"hanzi-preschool/count-nine","translation":"九个","recognition":true,"sourceSection":"语文园地一","imageChoice":true},{"word":"十","phonetic":"shí","exampleWord":"十个","exampleSentence":"盒子里有十个球。","image":"hanzi-preschool/count-ten","translation":"十个","recognition":true,"sourceSection":"语文园地一","imageChoice":true}]}',7,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字一';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·拼音与生活一',4,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活一 · 1（马路土本）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":2,"items":[{"word":"马","phonetic":"mǎ","exampleWord":"小马","exampleSentence":"小马在草地上跑。","image":"english-animal/horse","translation":"小马","recognition":true,"sourceSection":"d t n l","imageChoice":true},{"word":"路","exampleWord":"马路","exampleSentence":"汽车停在马路边。","image":"transport/car","imageChoice":false,"phonetic":"lù","translation":"马路","recognition":true,"sourceSection":"d t n l"},{"word":"土","phonetic":"tǔ","exampleWord":"泥土","exampleSentence":"小苗从泥土里长出来。","image":"hanzi-preschool/soil","translation":"泥土","recognition":true,"sourceSection":"d t n l","imageChoice":true},{"word":"本","phonetic":"běn","exampleWord":"本子","exampleSentence":"我的本子很整洁。","image":"english-school/notebook","translation":"本子","recognition":true,"sourceSection":"语文园地二","imageChoice":true}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活一 · 2（学校班级）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":2,"items":[{"word":"学","phonetic":"xué","exampleWord":"学习","exampleSentence":"我喜欢学习新本领。","image":"hanzi-preschool/learn","imageChoice":false,"translation":"学习","recognition":true,"sourceSection":"语文园地二"},{"word":"校","phonetic":"xiào","exampleWord":"学校","exampleSentence":"我们去参观学校。","image":"english-place/school","translation":"学校","recognition":true,"sourceSection":"语文园地二","imageChoice":true},{"word":"班","exampleWord":"班级","exampleSentence":"我们在班级里听故事。","image":"english-career/teacher","imageChoice":false,"phonetic":"bān","translation":"班级","recognition":true,"sourceSection":"语文园地二"},{"word":"级","exampleWord":"年级","exampleSentence":"一年级的小朋友喜欢看书。","image":"english-action/read","imageChoice":false,"phonetic":"jí","translation":"年级","recognition":true,"sourceSection":"语文园地二"}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活一 · 3（姓名王）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":2,"items":[{"word":"姓","exampleWord":"姓氏","exampleSentence":"老师正在介绍自己的姓氏。","image":"english-career/teacher","imageChoice":false,"phonetic":"xìng","translation":"姓氏","recognition":true,"sourceSection":"语文园地二"},{"word":"名","exampleWord":"名字","exampleSentence":"老师告诉大家自己的名字。","image":"english-career/teacher","imageChoice":false,"phonetic":"míng","translation":"名字","recognition":true,"sourceSection":"语文园地二"},{"word":"王","exampleWord":"王子","exampleSentence":"王子戴着一顶王冠。","image":"hanzi-preschool/prince","imageChoice":true,"phonetic":"wáng","translation":"王子","recognition":true,"sourceSection":"语文园地二"}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活一';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·拼音与生活二',5,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活二 · 1（画打棋积）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":3,"items":[{"word":"画","exampleWord":"画画","exampleSentence":"小朋友坐下来画画。","image":"chinese-pinyin/drawing-picture","imageChoice":true,"phonetic":"huà","translation":"画画","recognition":true,"sourceSection":"g k h"},{"word":"打","exampleWord":"打球","exampleSentence":"我们在草地上打球。","image":"hanzi-preschool/ball-play","imageChoice":false,"phonetic":"dǎ","translation":"打球","recognition":true,"sourceSection":"j q x"},{"word":"棋","exampleWord":"棋子","exampleSentence":"桌上摆着棋子。","image":"hanzi-preschool/chess-pieces","imageChoice":true,"phonetic":"qí","translation":"棋子","recognition":true,"sourceSection":"j q x"},{"word":"积","exampleWord":"积木","exampleSentence":"我用积木搭小桥。","image":"chinese-pinyin/building-blocks","imageChoice":true,"phonetic":"jī","translation":"积木","recognition":true,"sourceSection":"j q x"}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活二 · 2（字词句子）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":3,"items":[{"word":"字","exampleWord":"汉字","exampleSentence":"我在纸上写一个汉字。","image":"hanzi-preschool/write-character","imageChoice":false,"phonetic":"zì","translation":"汉字","recognition":true,"sourceSection":"z c s"},{"word":"词","exampleWord":"词语","exampleSentence":"老师带我们读词语。","image":"english-career/teacher","imageChoice":false,"phonetic":"cí","translation":"词语","recognition":true,"sourceSection":"z c s"},{"word":"句","exampleWord":"句子","exampleSentence":"老师读了一句短句子。","image":"english-career/teacher","imageChoice":false,"phonetic":"jù","translation":"句子","recognition":true,"sourceSection":"z c s"},{"word":"子","exampleWord":"子女","exampleSentence":"子女和爸爸妈妈在一起。","image":"english-family/family","imageChoice":false,"phonetic":"zǐ","translation":"子女","recognition":true,"sourceSection":"z c s"}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活二 · 3（桌纸读书）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":3,"items":[{"word":"桌","exampleWord":"桌子","exampleSentence":"桌子上摆着一本书。","image":"hanzi-preschool/desk","imageChoice":true,"phonetic":"zhuō","translation":"桌子","recognition":true,"sourceSection":"zh ch sh r"},{"word":"纸","phonetic":"zhǐ","exampleWord":"白纸","exampleSentence":"我在白纸上画花。","image":"hanzi-preschool/paper","translation":"白纸","recognition":true,"sourceSection":"zh ch sh r","imageChoice":true},{"word":"读","exampleWord":"读书","exampleSentence":"我坐下来读书。","image":"english-action/read","imageChoice":false,"phonetic":"dú","translation":"读书","recognition":true,"sourceSection":"zh ch sh r"},{"word":"书","phonetic":"shū","exampleWord":"图书","exampleSentence":"我把图书放回原处。","image":"hanzi-preschool/book","translation":"图书","recognition":true,"sourceSection":"zh ch sh r","imageChoice":true}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活二 · 4（鱼鸭乌鸦）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":3,"items":[{"word":"鱼","phonetic":"yú","exampleWord":"小鱼","exampleSentence":"小鱼在水里游。","image":"chinese-pinyin/colorful-fish","translation":"小鱼","recognition":true,"sourceSection":"y w","imageChoice":true},{"word":"鸭","phonetic":"yā","exampleWord":"鸭子","exampleSentence":"鸭子在水边走。","image":"english-farm-baby/duck","translation":"鸭子","recognition":true,"sourceSection":"y w","imageChoice":true},{"word":"乌","exampleWord":"乌黑","exampleSentence":"这只乌鸦的羽毛乌黑。","image":"chinese-pinyin/black-crow","imageChoice":true,"phonetic":"wū","translation":"乌黑","recognition":true,"sourceSection":"y w"},{"word":"鸦","exampleWord":"乌鸦","exampleSentence":"乌鸦站在树枝上。","image":"chinese-pinyin/black-crow","imageChoice":true,"phonetic":"yā","translation":"乌鸦","recognition":true,"sourceSection":"y w"}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活二 · 5（午星期语）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":3,"items":[{"word":"午","exampleWord":"中午","exampleSentence":"中午，太阳升得很高。","image":"hanzi-pilot/hanzi-ri","imageChoice":false,"phonetic":"wǔ","translation":"中午","recognition":true,"sourceSection":"语文园地三"},{"word":"星","exampleWord":"星星","exampleSentence":"夜空里有一颗星星。","image":"english-nature/star","imageChoice":true,"phonetic":"xīng","translation":"星星","recognition":true,"sourceSection":"语文园地三"},{"word":"期","exampleWord":"星期","exampleSentence":"星期天，我和妈妈一起看书。","image":"english-action/read","imageChoice":false,"phonetic":"qī","translation":"星期","recognition":true,"sourceSection":"语文园地三"},{"word":"语","exampleWord":"语言","exampleSentence":"我们用语言说出想法。","image":"chinese-pinyin/child-speaking-a","imageChoice":false,"phonetic":"yǔ","translation":"语言","recognition":true,"sourceSection":"语文园地三"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活二 · 6（文数写会）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":3,"items":[{"word":"文","exampleWord":"图文","exampleSentence":"图文故事很有趣。","image":"english-action/read","imageChoice":false,"phonetic":"wén","translation":"图文","recognition":true,"sourceSection":"语文园地三"},{"word":"数","exampleWord":"数字","exampleSentence":"我看着积木认识数字。","image":"chinese-pinyin/eight-blocks","imageChoice":false,"phonetic":"shù","translation":"数字","recognition":true,"sourceSection":"语文园地三","readingNote":"本课读 shù（数字）；教材另学 shǔ（数一数）。"},{"word":"写","exampleWord":"写字","exampleSentence":"我在纸上认真写字。","image":"hanzi-preschool/write-character","imageChoice":false,"phonetic":"xiě","translation":"写字","recognition":true,"sourceSection":"语文园地三"},{"word":"会","exampleWord":"学会","exampleSentence":"我学会了搭积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"huì","translation":"学会","recognition":true,"sourceSection":"语文园地三"}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活二';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·拼音与生活三',6,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 1（白菜西瓜）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"白","exampleWord":"白色","exampleSentence":"白色的小鹅站在草地上。","image":"chinese-pinyin/white-goose","imageChoice":true,"phonetic":"bái","translation":"白色","recognition":true,"sourceSection":"ai ei ui"},{"word":"菜","phonetic":"cài","exampleWord":"青菜","exampleSentence":"我爱吃青菜。","image":"hanzi-preschool/vegetable","translation":"青菜","recognition":true,"sourceSection":"ai ei ui","imageChoice":true},{"word":"西","exampleWord":"西瓜","exampleSentence":"桌上有一块西瓜。","image":"fruit/watermelon","imageChoice":false,"phonetic":"xī","translation":"西瓜","recognition":true,"sourceSection":"ai ei ui"},{"word":"瓜","phonetic":"guā","exampleWord":"西瓜","exampleSentence":"桌上有一块西瓜。","image":"fruit/watermelon","translation":"西瓜","recognition":true,"sourceSection":"ai ei ui","imageChoice":true}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 2（果桥流柳）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"果","phonetic":"guǒ","exampleWord":"苹果","exampleSentence":"我把苹果洗干净。","image":"fruit/apple","translation":"苹果","recognition":true,"sourceSection":"ai ei ui","imageChoice":true},{"word":"桥","exampleWord":"小桥","exampleSentence":"河上有一座小桥。","image":"hanzi-preschool/bridge","imageChoice":true,"phonetic":"qiáo","translation":"小桥","recognition":true,"sourceSection":"ao ou iu"},{"word":"流","exampleWord":"流水","exampleSentence":"流水从小山旁经过。","image":"hanzi-pilot/hanzi-shui","imageChoice":false,"phonetic":"liú","translation":"流水","recognition":true,"sourceSection":"ao ou iu"},{"word":"柳","exampleWord":"柳树","exampleSentence":"柳树垂下长长的枝条。","image":"hanzi-preschool/willow","imageChoice":true,"phonetic":"liǔ","translation":"柳树","recognition":true,"sourceSection":"ao ou iu"}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 3（开夜色美）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"开","phonetic":"kāi","exampleWord":"打开","exampleSentence":"我把盒子打开了。","image":"hanzi-preschool/open-box","translation":"打开","recognition":true,"sourceSection":"ie üe er","imageChoice":true},{"word":"夜","exampleWord":"夜晚","exampleSentence":"夜晚，月亮出来了。","image":"hanzi-pilot/hanzi-yue","imageChoice":false,"phonetic":"yè","translation":"夜晚","recognition":true,"sourceSection":"ie üe er"},{"word":"色","exampleWord":"颜色","exampleSentence":"这个球的颜色是红色。","image":"hanzi-preschool/red","imageChoice":false,"phonetic":"sè","translation":"颜色","recognition":true,"sourceSection":"ie üe er"},{"word":"美","exampleWord":"美丽","exampleSentence":"美丽的红花开了。","image":"hanzi-pilot/hanzi-hua","imageChoice":false,"phonetic":"měi","translation":"美丽","recognition":true,"sourceSection":"ie üe er"}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 4（蓝原冰自）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"蓝","phonetic":"lán","exampleWord":"蓝色","exampleSentence":"我有一个蓝色的球。","image":"hanzi-preschool/blue","translation":"蓝色","recognition":true,"sourceSection":"an en in un ün","imageChoice":true},{"word":"原","exampleWord":"草原","exampleSentence":"草原上有一匹马。","image":"english-animal/horse","imageChoice":false,"phonetic":"yuán","translation":"草原","recognition":true,"sourceSection":"an en in un ün"},{"word":"冰","exampleWord":"冰块","exampleSentence":"碗里有几块透明的冰块。","image":"hanzi-preschool/ice","imageChoice":true,"phonetic":"bīng","translation":"冰块","recognition":true,"sourceSection":"ang eng ing ong"},{"word":"自","exampleWord":"自己","exampleSentence":"我自己搭好了积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"zì","translation":"自己","recognition":true,"sourceSection":"ang eng ing ong"}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 5（行车晚昨）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"行","exampleWord":"行走","exampleSentence":"小朋友在路上慢慢行走。","image":"hanzi-preschool/walk","imageChoice":false,"phonetic":"xíng","translation":"行走","recognition":true,"sourceSection":"ang eng ing ong"},{"word":"车","phonetic":"chē","exampleWord":"汽车","exampleSentence":"汽车停在路边。","image":"transport/car","translation":"汽车","recognition":true,"sourceSection":"ang eng ing ong","imageChoice":true},{"word":"晚","exampleWord":"晚上","exampleSentence":"晚上，我准备睡觉。","image":"hanzi-preschool/sleep","imageChoice":false,"phonetic":"wǎn","translation":"晚上","recognition":true,"sourceSection":"语文园地四"},{"word":"昨","exampleWord":"昨天","exampleSentence":"昨天，我们一起画了画。","image":"chinese-pinyin/drawing-picture","imageChoice":false,"phonetic":"zuó","translation":"昨天","recognition":true,"sourceSection":"语文园地四"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 6（今明个这）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"今","exampleWord":"今天","exampleSentence":"今天，我们一起看书。","image":"english-action/read","imageChoice":false,"phonetic":"jīn","translation":"今天","recognition":true,"sourceSection":"语文园地四"},{"word":"明","exampleWord":"明亮","exampleSentence":"明亮的台灯照着桌面。","image":"home/lamp","imageChoice":false,"phonetic":"míng","translation":"明亮","recognition":true,"sourceSection":"语文园地四"},{"word":"个","phonetic":"gè","exampleWord":"一个","exampleSentence":"我有一个皮球。","image":"hanzi-preschool/single-ball","translation":"一个","recognition":true,"sourceSection":"语文园地四","imageChoice":true},{"word":"这","exampleWord":"这个","exampleSentence":"这个苹果红红的。","image":"fruit/apple","imageChoice":false,"phonetic":"zhè","translation":"这个","recognition":true,"sourceSection":"语文园地四"}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'拼音与生活三 · 7（去年）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":4,"items":[{"word":"去","exampleWord":"去看","exampleSentence":"我去看书架上的图书。","image":"english-action/read","imageChoice":false,"phonetic":"qù","translation":"去看","recognition":true,"sourceSection":"语文园地四"},{"word":"年","exampleWord":"新年","exampleSentence":"新年到了，我们挂起红灯笼。","image":"hanzi-preschool/new-year","imageChoice":false,"phonetic":"nián","translation":"新年","recognition":true,"sourceSection":"语文园地四"}]}',7,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·拼音与生活三';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·阅读一',7,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 1（秋气了叶）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"秋","exampleWord":"秋天","exampleSentence":"秋天，树叶变黄了。","image":"hanzi-preschool/autumn","imageChoice":false,"phonetic":"qiū","translation":"秋天","recognition":true,"sourceSection":"秋天"},{"word":"气","exampleWord":"空气","exampleSentence":"小朋友在新鲜空气里散步。","image":"hanzi-preschool/walk","imageChoice":false,"phonetic":"qì","translation":"空气","recognition":true,"sourceSection":"秋天"},{"word":"了","exampleWord":"开了","exampleSentence":"花儿开了。","image":"hanzi-pilot/hanzi-hua","imageChoice":false,"phonetic":"le","translation":"开了","recognition":true,"sourceSection":"秋天"},{"word":"叶","phonetic":"yè","exampleWord":"树叶","exampleSentence":"一片树叶落下了。","image":"english-nature/leaf","translation":"树叶","recognition":true,"sourceSection":"秋天","imageChoice":true}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 2（黄片从来）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"黄","phonetic":"huáng","exampleWord":"黄色","exampleSentence":"我有一个黄色的球。","image":"hanzi-preschool/yellow","translation":"黄色","recognition":true,"sourceSection":"秋天","imageChoice":true},{"word":"片","exampleWord":"一片","exampleSentence":"地上有一片树叶。","image":"english-nature/leaf","imageChoice":true,"phonetic":"piàn","translation":"一片","recognition":true,"sourceSection":"秋天"},{"word":"从","exampleWord":"从小","exampleSentence":"小树从小苗慢慢长大。","image":"hanzi-pilot/hanzi-shu","imageChoice":false,"phonetic":"cóng","translation":"从小","recognition":true,"sourceSection":"秋天"},{"word":"来","exampleWord":"来到","exampleSentence":"小朋友来到草地上。","image":"hanzi-preschool/walk","imageChoice":false,"phonetic":"lái","translation":"来到","recognition":true,"sourceSection":"秋天"}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 3（飞江南可）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"飞","phonetic":"fēi","exampleWord":"飞翔","exampleSentence":"小鸟张开翅膀飞翔。","image":"hanzi-preschool/flying-bird","translation":"飞翔","recognition":true,"sourceSection":"秋天","imageChoice":true},{"word":"江","exampleWord":"江水","exampleSentence":"江水缓缓向前流。","image":"hanzi-pilot/hanzi-shui","imageChoice":true,"phonetic":"jiāng","translation":"江水","recognition":true,"sourceSection":"江南"},{"word":"南","exampleWord":"南方","exampleSentence":"我们在南方见到荷花。","image":"hanzi-preschool/lotus","imageChoice":false,"phonetic":"nán","translation":"南方","recognition":true,"sourceSection":"江南"},{"word":"可","exampleWord":"可以","exampleSentence":"我可以自己搭积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"kě","translation":"可以","recognition":true,"sourceSection":"江南"}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 4（采莲戏间）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"采","exampleWord":"采摘","exampleSentence":"小朋友在篮子里放入采摘的苹果。","image":"hanzi-preschool/pick-apples","imageChoice":false,"phonetic":"cǎi","translation":"采摘","recognition":true,"sourceSection":"江南"},{"word":"莲","exampleWord":"莲花","exampleSentence":"莲花开在水面上。","image":"hanzi-preschool/lotus","imageChoice":true,"phonetic":"lián","translation":"莲花","recognition":true,"sourceSection":"江南"},{"word":"戏","exampleWord":"游戏","exampleSentence":"小朋友们在草地上做游戏。","image":"hanzi-preschool/ball-play","imageChoice":false,"phonetic":"xì","translation":"游戏","recognition":true,"sourceSection":"江南"},{"word":"间","exampleWord":"中间","exampleSentence":"两个孩子中间有一个球。","image":"hanzi-preschool/between","imageChoice":false,"phonetic":"jiān","translation":"中间","recognition":true,"sourceSection":"江南"}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 5（东北的家）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"东","exampleWord":"东方","exampleSentence":"太阳从东方升起。","image":"hanzi-pilot/hanzi-ri","imageChoice":false,"phonetic":"dōng","translation":"东方","recognition":true,"sourceSection":"江南"},{"word":"北","exampleWord":"北方","exampleSentence":"北方的冬天有白雪。","image":"hanzi-pilot/hanzi-xue","imageChoice":false,"phonetic":"běi","translation":"北方","recognition":true,"sourceSection":"江南"},{"word":"的","exampleWord":"我的","exampleSentence":"这是我的书包。","image":"english-school/backpack","imageChoice":false,"phonetic":"de","translation":"我的","recognition":true,"sourceSection":"雪地里的小画家"},{"word":"家","exampleWord":"家人","exampleSentence":"家人聚在一起。","image":"english-family/family","imageChoice":false,"phonetic":"jiā","translation":"家人","recognition":true,"sourceSection":"雪地里的小画家"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 6（鸡竹牙用）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"鸡","phonetic":"jī","exampleWord":"公鸡","exampleSentence":"公鸡站在草地上。","image":"chinese-pinyin/rooster-crowing","translation":"公鸡","recognition":true,"sourceSection":"雪地里的小画家","imageChoice":true},{"word":"竹","phonetic":"zhú","exampleWord":"竹子","exampleSentence":"竹子长得高高的。","image":"hanzi-preschool/bamboo","translation":"竹子","recognition":true,"sourceSection":"雪地里的小画家","imageChoice":true},{"word":"牙","phonetic":"yá","exampleWord":"牙齿","exampleSentence":"我每天刷牙。","image":"hanzi-preschool/tooth","translation":"牙齿","recognition":true,"sourceSection":"雪地里的小画家","imageChoice":true},{"word":"用","exampleWord":"使用","exampleSentence":"我使用铅笔画画。","image":"english-school/pencil","imageChoice":false,"phonetic":"yòng","translation":"使用","recognition":true,"sourceSection":"雪地里的小画家"}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 7（几步没参）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"几","exampleWord":"几个","exampleSentence":"桌上有几个积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"jǐ","translation":"几个","recognition":true,"sourceSection":"雪地里的小画家"},{"word":"步","exampleWord":"脚步","exampleSentence":"我迈着脚步慢慢走。","image":"hanzi-preschool/walk","imageChoice":false,"phonetic":"bù","translation":"脚步","recognition":true,"sourceSection":"雪地里的小画家"},{"word":"没","exampleWord":"没有","exampleSentence":"盒子里没有东西。","image":"hanzi-preschool/open-box","imageChoice":false,"phonetic":"méi","translation":"没有","recognition":true,"sourceSection":"雪地里的小画家"},{"word":"参","exampleWord":"参加","exampleSentence":"小朋友参加搭积木的活动。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"cān","translation":"参加","recognition":true,"sourceSection":"雪地里的小画家"}]}',7,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 8（加鸟说是）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"加","exampleWord":"加入","exampleSentence":"小朋友加入大家的游戏。","image":"hanzi-preschool/ball-play","imageChoice":false,"phonetic":"jiā","translation":"加入","recognition":true,"sourceSection":"雪地里的小画家"},{"word":"鸟","phonetic":"niǎo","exampleWord":"小鸟","exampleSentence":"小鸟站在树上。","image":"hanzi-preschool/bird","translation":"小鸟","recognition":true,"sourceSection":"四季","imageChoice":true},{"word":"说","phonetic":"shuō","exampleWord":"说话","exampleSentence":"大家轮流说话。","image":"chinese-pinyin/child-speaking-a","translation":"说话","recognition":true,"sourceSection":"四季","imageChoice":true},{"word":"是","exampleWord":"这是","exampleSentence":"这是一棵大树。","image":"hanzi-pilot/hanzi-shu","imageChoice":false,"phonetic":"shì","translation":"这是","recognition":true,"sourceSection":"四季"}]}',8,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 9（春青蛙夏）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"春","exampleWord":"春天","exampleSentence":"春天，小苗发芽了。","image":"hanzi-preschool/rice-seedling","imageChoice":false,"phonetic":"chūn","translation":"春天","recognition":true,"sourceSection":"四季"},{"word":"青","exampleWord":"青草","exampleSentence":"青草绿绿的。","image":"hanzi-pilot/hanzi-cao","imageChoice":false,"phonetic":"qīng","translation":"青草","recognition":true,"sourceSection":"四季"},{"word":"蛙","phonetic":"wā","exampleWord":"青蛙","exampleSentence":"青蛙蹲在荷叶上。","image":"hanzi-preschool/frog","translation":"青蛙","recognition":true,"sourceSection":"四季","imageChoice":true},{"word":"夏","exampleWord":"夏天","exampleSentence":"夏天，我在树下乘凉。","image":"hanzi-pilot/hanzi-shu","imageChoice":false,"phonetic":"xià","translation":"夏天","recognition":true,"sourceSection":"四季"}]}',9,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 10（着皮就冬）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"着","exampleWord":"看着","exampleSentence":"小朋友看着图书。","image":"english-action/read","imageChoice":false,"phonetic":"zhe","translation":"看着","recognition":true,"sourceSection":"四季","readingNote":"本课读 zhe（看着）；教材另学 zháo（喝不着）。"},{"word":"皮","exampleWord":"果皮","exampleSentence":"橙子的果皮是橙色的。","image":"fruit/orange","imageChoice":false,"phonetic":"pí","translation":"果皮","recognition":true,"sourceSection":"四季"},{"word":"就","exampleWord":"就能","exampleSentence":"坐下来就能安心看书。","image":"english-action/read","imageChoice":false,"phonetic":"jiù","translation":"就能","recognition":true,"sourceSection":"四季"},{"word":"冬","exampleWord":"冬天","exampleSentence":"冬天，地上有白雪。","image":"hanzi-pilot/hanzi-xue","imageChoice":false,"phonetic":"dōng","translation":"冬天","recognition":true,"sourceSection":"四季"}]}',10,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 11（男女关正）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"男","exampleWord":"男孩","exampleSentence":"男孩在搭积木。","image":"chinese-pinyin/building-blocks","imageChoice":true,"phonetic":"nán","translation":"男孩","recognition":true,"sourceSection":"语文园地五"},{"word":"女","exampleWord":"女孩","exampleSentence":"女孩站在草地上。","image":"english-family/sister","imageChoice":true,"phonetic":"nǚ","translation":"女孩","recognition":true,"sourceSection":"语文园地五"},{"word":"关","phonetic":"guān","exampleWord":"关上","exampleSentence":"我把盒子关上了。","image":"hanzi-preschool/closed-box","translation":"关上","recognition":true,"sourceSection":"语文园地五","imageChoice":true},{"word":"正","exampleWord":"正面","exampleSentence":"玩具熊的正面朝着我。","image":"hanzi-preschool/front-bear","imageChoice":false,"phonetic":"zhèng","translation":"正面","recognition":true,"sourceSection":"语文园地五"}]}',11,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 12（反先后）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"反","exampleWord":"反面","exampleSentence":"玩具熊的反面朝着我。","image":"hanzi-preschool/back-bear","imageChoice":false,"phonetic":"fǎn","translation":"反面","recognition":true,"sourceSection":"语文园地五"},{"word":"先","exampleWord":"先洗手","exampleSentence":"我先洗手，再吃饭。","image":"english-action/wash","imageChoice":false,"phonetic":"xiān","translation":"先洗手","recognition":true,"sourceSection":"语文园地五"},{"word":"后","exampleWord":"后面","exampleSentence":"球在盒子的后面。","image":"hanzi-preschool/behind-box","imageChoice":false,"phonetic":"hòu","translation":"后面","recognition":true,"sourceSection":"语文园地五"}]}',12,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读一 · 13（内外）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":5,"items":[{"word":"内","exampleWord":"内部","exampleSentence":"球在盒子的内部。","image":"hanzi-preschool/inside-box","imageChoice":false,"phonetic":"nèi","translation":"内部","recognition":true,"sourceSection":"语文园地五"},{"word":"外","exampleWord":"外面","exampleSentence":"球在盒子的外面。","image":"hanzi-preschool/outside-box","imageChoice":false,"phonetic":"wài","translation":"外面","recognition":true,"sourceSection":"语文园地五"}]}',13,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读一';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·识字二',8,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 1（对歌虫清）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"对","exampleWord":"答对","exampleSentence":"我答对了，开心地笑了。","image":"hanzi-preschool/smile","imageChoice":false,"phonetic":"duì","translation":"答对","recognition":true,"sourceSection":"对韵歌"},{"word":"歌","exampleWord":"唱歌","exampleSentence":"小朋友张开嘴唱歌。","image":"chinese-pinyin/child-speaking-a","imageChoice":false,"phonetic":"gē","translation":"唱歌","recognition":true,"sourceSection":"对韵歌"},{"word":"虫","phonetic":"chóng","exampleWord":"小虫","exampleSentence":"叶子上有一只小虫。","image":"hanzi-preschool/caterpillar","translation":"小虫","recognition":true,"sourceSection":"对韵歌","imageChoice":true},{"word":"清","exampleWord":"清水","exampleSentence":"清水缓缓流过石头。","image":"hanzi-pilot/hanzi-shui","imageChoice":false,"phonetic":"qīng","translation":"清水","recognition":true,"sourceSection":"对韵歌"}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 2（绿桃红力）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"绿","phonetic":"lǜ","exampleWord":"绿色","exampleSentence":"我有一个绿色的球。","image":"hanzi-preschool/green","translation":"绿色","recognition":true,"sourceSection":"对韵歌","imageChoice":true},{"word":"桃","exampleWord":"桃子","exampleSentence":"桃子摆在盘子里。","image":"fruit/peach","imageChoice":false,"phonetic":"táo","translation":"桃子","recognition":true,"sourceSection":"对韵歌"},{"word":"红","phonetic":"hóng","exampleWord":"红色","exampleSentence":"我有一个红色的球。","image":"hanzi-preschool/red","translation":"红色","recognition":true,"sourceSection":"对韵歌","imageChoice":true},{"word":"力","exampleWord":"力气","exampleSentence":"我用力气推小车。","image":"chinese-pinyin/pull-wagon","imageChoice":false,"phonetic":"lì","translation":"力气","recognition":true,"sourceSection":"日月明"}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 3（尖尘众双）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"尖","exampleWord":"笔尖","exampleSentence":"铅笔的笔尖细细的。","image":"english-school/pencil","imageChoice":false,"phonetic":"jiān","translation":"笔尖","recognition":true,"sourceSection":"日月明"},{"word":"尘","exampleWord":"灰尘","exampleSentence":"扫帚把地上的灰尘扫起来。","image":"hanzi-preschool/dust","imageChoice":false,"phonetic":"chén","translation":"灰尘","recognition":true,"sourceSection":"日月明"},{"word":"众","exampleWord":"众人","exampleSentence":"众人聚在一起。","image":"english-family/family","imageChoice":false,"phonetic":"zhòng","translation":"众人","recognition":true,"sourceSection":"日月明"},{"word":"双","phonetic":"shuāng","exampleWord":"一双","exampleSentence":"这是一双手套。","image":"hanzi-preschool/pair-gloves","translation":"一双","recognition":true,"sourceSection":"日月明","imageChoice":true}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 4（林森不条）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"林","exampleWord":"树林","exampleSentence":"树林里有几棵树。","image":"hanzi-preschool/forest","imageChoice":false,"phonetic":"lín","translation":"树林","recognition":true,"sourceSection":"日月明"},{"word":"森","exampleWord":"森林","exampleSentence":"森林里的树很多。","image":"hanzi-preschool/forest","imageChoice":false,"phonetic":"sēn","translation":"森林","recognition":true,"sourceSection":"日月明"},{"word":"不","exampleWord":"不哭","exampleSentence":"小朋友不哭，露出了微笑。","image":"hanzi-preschool/smile","imageChoice":false,"phonetic":"bù","translation":"不哭","recognition":true,"sourceSection":"日月明"},{"word":"条","exampleWord":"一条","exampleSentence":"地上放着一条长绳。","image":"hanzi-preschool/long-rope","imageChoice":false,"phonetic":"tiáo","translation":"一条","recognition":true,"sourceSection":"日月明"}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 5（心金包尺）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"心","phonetic":"xīn","exampleWord":"爱心","exampleSentence":"我画了一颗爱心。","image":"hanzi-preschool/heart","translation":"爱心","recognition":true,"sourceSection":"日月明","imageChoice":true},{"word":"金","exampleWord":"金色","exampleSentence":"金色的奖牌亮亮的。","image":"chinese-pinyin/gold-medal","imageChoice":true,"phonetic":"jīn","translation":"金色","recognition":true,"sourceSection":"日月明"},{"word":"包","phonetic":"bāo","exampleWord":"书包","exampleSentence":"我的书包很轻。","image":"english-school/backpack","translation":"书包","recognition":true,"sourceSection":"小书包","imageChoice":true},{"word":"尺","exampleWord":"尺子","exampleSentence":"桌上有一把尺子。","image":"english-school/ruler","imageChoice":true,"phonetic":"chǐ","translation":"尺子","recognition":true,"sourceSection":"小书包"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 6（作业笔刀）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"作","exampleWord":"作业","exampleSentence":"我用铅笔完成作业。","image":"hanzi-preschool/write-character","imageChoice":false,"phonetic":"zuò","translation":"作业","recognition":true,"sourceSection":"小书包"},{"word":"业","exampleWord":"作业","exampleSentence":"我把作业写整齐。","image":"hanzi-preschool/write-character","imageChoice":false,"phonetic":"yè","translation":"作业","recognition":true,"sourceSection":"小书包"},{"word":"笔","phonetic":"bǐ","exampleWord":"铅笔","exampleSentence":"我用铅笔画画。","image":"english-school/pencil","translation":"铅笔","recognition":true,"sourceSection":"小书包","imageChoice":true},{"word":"刀","exampleWord":"剪刀","exampleSentence":"这把儿童剪刀的尖头是圆的。","image":"hanzi-preschool/scissors","imageChoice":true,"phonetic":"dāo","translation":"剪刀","recognition":true,"sourceSection":"小书包"}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 7（宝贝课早）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"宝","exampleWord":"宝贝","exampleSentence":"我的宝贝玩具熊很软。","image":"hanzi-preschool/toy-bear","imageChoice":false,"phonetic":"bǎo","translation":"宝贝","recognition":true,"sourceSection":"小书包"},{"word":"贝","exampleWord":"贝壳","exampleSentence":"沙滩上有一枚贝壳。","image":"hanzi-preschool/shell","imageChoice":true,"phonetic":"bèi","translation":"贝壳","recognition":true,"sourceSection":"小书包"},{"word":"课","exampleWord":"上课","exampleSentence":"上课时，大家认真听老师讲故事。","image":"english-career/teacher","imageChoice":false,"phonetic":"kè","translation":"上课","recognition":true,"sourceSection":"小书包"},{"word":"早","exampleWord":"早上","exampleSentence":"早上，太阳出来了。","image":"hanzi-pilot/hanzi-ri","imageChoice":false,"phonetic":"zǎo","translation":"早上","recognition":true,"sourceSection":"小书包"}]}',7,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 8（升国旗中）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"升","exampleWord":"升起","exampleSentence":"太阳慢慢升起。","image":"hanzi-pilot/hanzi-ri","imageChoice":false,"phonetic":"shēng","translation":"升起","recognition":true,"sourceSection":"升国旗"},{"word":"国","exampleWord":"祖国","exampleSentence":"我们爱祖国的五星红旗。","image":"hanzi-preschool/national-flag","imageChoice":false,"phonetic":"guó","translation":"祖国","recognition":true,"sourceSection":"升国旗"},{"word":"旗","exampleWord":"红旗","exampleSentence":"五星红旗在旗杆上飘扬。","image":"hanzi-preschool/national-flag","imageChoice":true,"phonetic":"qí","translation":"红旗","recognition":true,"sourceSection":"升国旗"},{"word":"中","exampleWord":"中间","exampleSentence":"两个孩子中间有一个球。","image":"hanzi-preschool/between","imageChoice":false,"phonetic":"zhōng","translation":"中间","recognition":true,"sourceSection":"升国旗"}]}',8,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 9（们声起么）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"们","exampleWord":"我们","exampleSentence":"我们一起分享玩具。","image":"english-action/share","imageChoice":false,"phonetic":"men","translation":"我们","recognition":true,"sourceSection":"升国旗"},{"word":"声","exampleWord":"声音","exampleSentence":"老师讲故事的声音很清楚。","image":"english-career/teacher","imageChoice":false,"phonetic":"shēng","translation":"声音","recognition":true,"sourceSection":"升国旗"},{"word":"起","exampleWord":"起身","exampleSentence":"小朋友从椅子上起身。","image":"hanzi-preschool/stand-up","imageChoice":false,"phonetic":"qǐ","translation":"起身","recognition":true,"sourceSection":"升国旗"},{"word":"么","exampleWord":"什么","exampleSentence":"你在看什么图书？","image":"english-action/read","imageChoice":false,"phonetic":"me","translation":"什么","recognition":true,"sourceSection":"升国旗"}]}',9,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 10（向立老师）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"向","exampleWord":"向上","exampleSentence":"小鸟向上飞。","image":"hanzi-preschool/flying-bird","imageChoice":false,"phonetic":"xiàng","translation":"向上","recognition":true,"sourceSection":"升国旗"},{"word":"立","exampleWord":"站立","exampleSentence":"小朋友站立在草地上。","image":"hanzi-preschool/body","imageChoice":false,"phonetic":"lì","translation":"站立","recognition":true,"sourceSection":"升国旗"},{"word":"老","phonetic":"lǎo","exampleWord":"老人","exampleSentence":"我们给老人让座。","image":"hanzi-preschool/elder","translation":"老人","recognition":true,"sourceSection":"语文园地六","imageChoice":true},{"word":"师","phonetic":"shī","exampleWord":"老师","exampleSentence":"老师给我们讲故事。","image":"english-career/teacher","translation":"老师","recognition":true,"sourceSection":"语文园地六","imageChoice":true}]}',10,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 11（工厂医院）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"工","exampleWord":"工人","exampleSentence":"工人戴着安全帽。","image":"english-career/builder","imageChoice":true,"phonetic":"gōng","translation":"工人","recognition":true,"sourceSection":"语文园地六"},{"word":"厂","exampleWord":"工厂","exampleSentence":"工厂外面有整齐的道路。","image":"hanzi-preschool/factory","imageChoice":true,"phonetic":"chǎng","translation":"工厂","recognition":true,"sourceSection":"语文园地六"},{"word":"医","exampleWord":"医生","exampleSentence":"医生用听诊器听心跳。","image":"hanzi-preschool/doctor","imageChoice":true,"phonetic":"yī","translation":"医生","recognition":true,"sourceSection":"语文园地六"},{"word":"院","exampleWord":"医院","exampleSentence":"医院是看病的地方。","image":"english-career/hospital","imageChoice":true,"phonetic":"yuàn","translation":"医院","recognition":true,"sourceSection":"语文园地六"}]}',11,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'识字二 · 12（生门卫）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":6,"items":[{"word":"生","exampleWord":"学生","exampleSentence":"学生背着书包去学校。","image":"english-school/backpack","imageChoice":false,"phonetic":"shēng","translation":"学生","recognition":true,"sourceSection":"语文园地六"},{"word":"门","phonetic":"mén","exampleWord":"开门","exampleSentence":"爸爸轻轻开门。","image":"hanzi-preschool/door","translation":"开门","recognition":true,"sourceSection":"语文园地六","imageChoice":true},{"word":"卫","exampleWord":"门卫","exampleSentence":"门卫站在校门旁。","image":"hanzi-preschool/school-guard","imageChoice":true,"phonetic":"wèi","translation":"门卫","recognition":true,"sourceSection":"语文园地六"}]}',12,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·识字二';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·阅读二',9,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 1（船弯儿两）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"船","phonetic":"chuán","exampleWord":"小船","exampleSentence":"小船停在水边。","image":"transport/boat","translation":"小船","recognition":true,"sourceSection":"小小的船","imageChoice":true},{"word":"弯","exampleWord":"弯弯","exampleSentence":"弯弯的月亮挂在天空。","image":"hanzi-pilot/hanzi-yue","imageChoice":false,"phonetic":"wān","translation":"弯弯","recognition":true,"sourceSection":"小小的船"},{"word":"儿","exampleWord":"儿童","exampleSentence":"儿童在草地上玩。","image":"hanzi-preschool/body","imageChoice":false,"phonetic":"ér","translation":"儿童","recognition":true,"sourceSection":"小小的船"},{"word":"两","exampleWord":"两个","exampleSentence":"两个小朋友一起玩球。","image":"hanzi-preschool/ball-play","imageChoice":false,"phonetic":"liǎng","translation":"两个","recognition":true,"sourceSection":"小小的船"}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 2（头在里看）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"头","phonetic":"tóu","exampleWord":"头发","exampleSentence":"我的头发很整齐。","image":"english-body/head","translation":"头发","recognition":true,"sourceSection":"小小的船","imageChoice":true},{"word":"在","exampleWord":"正在","exampleSentence":"小朋友正在看书。","image":"english-action/read","imageChoice":false,"phonetic":"zài","translation":"正在","recognition":true,"sourceSection":"小小的船"},{"word":"里","exampleWord":"里面","exampleSentence":"盒子里面有一个球。","image":"hanzi-preschool/inside-box","imageChoice":false,"phonetic":"lǐ","translation":"里面","recognition":true,"sourceSection":"小小的船"},{"word":"看","phonetic":"kàn","exampleWord":"看书","exampleSentence":"我坐下来认真看书。","image":"english-action/read","translation":"看书","recognition":true,"sourceSection":"小小的船","imageChoice":true}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 3（见闪影前）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"见","exampleWord":"看见","exampleSentence":"我看见树上有叶子。","image":"hanzi-pilot/hanzi-shu","imageChoice":false,"phonetic":"jiàn","translation":"看见","recognition":true,"sourceSection":"小小的船"},{"word":"闪","exampleWord":"闪亮","exampleSentence":"闪亮的星星在夜空里。","image":"english-nature/star","imageChoice":false,"phonetic":"shǎn","translation":"闪亮","recognition":true,"sourceSection":"小小的船"},{"word":"影","exampleWord":"影子","exampleSentence":"阳光下有小朋友的影子。","image":"hanzi-preschool/shadow","imageChoice":false,"phonetic":"yǐng","translation":"影子","recognition":true,"sourceSection":"影子"},{"word":"前","exampleWord":"前面","exampleSentence":"球在盒子的前面。","image":"hanzi-preschool/front-box","imageChoice":false,"phonetic":"qián","translation":"前面","recognition":true,"sourceSection":"影子"}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 4（常黑狗它）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"常","exampleWord":"经常","exampleSentence":"我经常和妈妈一起看书。","image":"english-action/read","imageChoice":false,"phonetic":"cháng","translation":"经常","recognition":true,"sourceSection":"影子"},{"word":"黑","exampleWord":"黑色","exampleSentence":"乌鸦的羽毛是黑色的。","image":"chinese-pinyin/black-crow","imageChoice":false,"phonetic":"hēi","translation":"黑色","recognition":true,"sourceSection":"影子"},{"word":"狗","phonetic":"gǒu","exampleWord":"小狗","exampleSentence":"小狗摇着尾巴。","image":"english-farm-baby/puppy","translation":"小狗","recognition":true,"sourceSection":"影子","imageChoice":true},{"word":"它","exampleWord":"它们","exampleSentence":"它们是可爱的小鸭。","image":"english-farm-baby/duck","imageChoice":false,"phonetic":"tā","translation":"它们","recognition":true,"sourceSection":"影子"}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 5（好朋友件）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"好","exampleWord":"好朋友","exampleSentence":"好朋友一起分享玩具。","image":"english-family/friend","imageChoice":false,"phonetic":"hǎo","translation":"好朋友","recognition":true,"sourceSection":"影子"},{"word":"朋","exampleWord":"朋友","exampleSentence":"我和朋友一起玩。","image":"english-family/friend","imageChoice":false,"phonetic":"péng","translation":"朋友","recognition":true,"sourceSection":"影子"},{"word":"友","exampleWord":"好友","exampleSentence":"我和好友一起玩。","image":"english-family/friend","imageChoice":false,"phonetic":"yǒu","translation":"好友","recognition":true,"sourceSection":"影子"},{"word":"件","exampleWord":"一件","exampleSentence":"椅子上有一件上衣。","image":"english-clothing/t-shirt","imageChoice":false,"phonetic":"jiàn","translation":"一件","recognition":true,"sourceSection":"两件宝"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 6（有和做也）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"有","exampleWord":"有个","exampleSentence":"桌上有个苹果。","image":"fruit/apple","imageChoice":false,"phonetic":"yǒu","translation":"有个","recognition":true,"sourceSection":"两件宝"},{"word":"和","exampleWord":"我和你","exampleSentence":"我和你一起分享玩具。","image":"english-action/share","imageChoice":false,"phonetic":"hé","translation":"我和你","recognition":true,"sourceSection":"两件宝"},{"word":"做","exampleWord":"做事","exampleSentence":"小朋友自己动手做事。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"zuò","translation":"做事","recognition":true,"sourceSection":"两件宝"},{"word":"也","exampleWord":"也会","exampleSentence":"我也会搭积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"yě","translation":"也会","recognition":true,"sourceSection":"两件宝"}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 7（办到又才）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"办","exampleWord":"办法","exampleSentence":"我想到了搭桥的办法。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"bàn","translation":"办法","recognition":true,"sourceSection":"两件宝"},{"word":"到","exampleWord":"来到","exampleSentence":"小朋友来到草地上。","image":"hanzi-preschool/walk","imageChoice":false,"phonetic":"dào","translation":"来到","recognition":true,"sourceSection":"两件宝"},{"word":"又","exampleWord":"又来","exampleSentence":"小朋友又来看图书了。","image":"english-action/read","imageChoice":false,"phonetic":"yòu","translation":"又来","recognition":true,"sourceSection":"两件宝"},{"word":"才","exampleWord":"才能","exampleSentence":"仔细观察才能搭好积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"cái","translation":"才能","recognition":true,"sourceSection":"两件宝"}]}',7,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 8（能爷奶叔）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"能","exampleWord":"能干","exampleSentence":"能干的小朋友自己搭好积木。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"néng","translation":"能干","recognition":true,"sourceSection":"两件宝"},{"word":"爷","phonetic":"yé","exampleWord":"爷爷","exampleSentence":"爷爷在散步。","image":"english-family/grandpa","translation":"爷爷","recognition":true,"sourceSection":"语文园地七","imageChoice":true},{"word":"奶","phonetic":"nǎi","exampleWord":"奶奶","exampleSentence":"奶奶笑了。","image":"english-family/grandma","translation":"奶奶","recognition":true,"sourceSection":"语文园地七","imageChoice":true},{"word":"叔","exampleWord":"叔叔","exampleSentence":"叔叔穿着整齐的衣服。","image":"chinese-pinyin/friendly-uncle","imageChoice":false,"phonetic":"shū","translation":"叔叔","recognition":true,"sourceSection":"语文园地七"}]}',8,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读二 · 9（姐妹）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":7,"items":[{"word":"姐","phonetic":"jiě","exampleWord":"姐姐","exampleSentence":"姐姐在看书。","image":"hanzi-preschool/sister-older","translation":"姐姐","recognition":true,"sourceSection":"语文园地七","imageChoice":true},{"word":"妹","phonetic":"mèi","exampleWord":"妹妹","exampleSentence":"妹妹在玩球。","image":"hanzi-preschool/sister-younger","translation":"妹妹","recognition":true,"sourceSection":"语文园地七","imageChoice":true}]}',9,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读二';

INSERT INTO unit (theme_id,name,sort_order,is_locked) VALUES (10,'2024一年级上·阅读三',10,0);

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 1（比尾巴谁）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"比","exampleWord":"比较","exampleSentence":"我比较两条绳子的长度。","image":"hanzi-preschool/long-rope","imageChoice":false,"phonetic":"bǐ","translation":"比较","recognition":true,"sourceSection":"比尾巴"},{"word":"尾","exampleWord":"尾巴","exampleSentence":"小狗的尾巴翘起来了。","image":"english-farm-baby/puppy","imageChoice":false,"phonetic":"wěi","translation":"尾巴","recognition":true,"sourceSection":"比尾巴"},{"word":"巴","exampleWord":"尾巴","exampleSentence":"小狗摇摇尾巴。","image":"english-farm-baby/puppy","imageChoice":false,"phonetic":"bā","translation":"尾巴","recognition":true,"sourceSection":"比尾巴"},{"word":"谁","exampleWord":"是谁","exampleSentence":"站在草地上的是谁？","image":"hanzi-preschool/body","imageChoice":false,"phonetic":"shuí","translation":"是谁","recognition":true,"sourceSection":"比尾巴"}]}',1,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 2（长短把伞）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"长","phonetic":"cháng","exampleWord":"长绳","exampleSentence":"这条长绳很长。","image":"hanzi-preschool/long-rope","translation":"长绳","recognition":true,"sourceSection":"比尾巴","imageChoice":true,"readingNote":"本课读 cháng（长绳）；教材另学 zhǎng（长大）。"},{"word":"短","phonetic":"duǎn","exampleWord":"短绳","exampleSentence":"这条短绳很短。","image":"hanzi-preschool/short-rope","translation":"短绳","recognition":true,"sourceSection":"比尾巴","imageChoice":true},{"word":"把","exampleWord":"一把","exampleSentence":"我有一把雨伞。","image":"hanzi-preschool/umbrella","imageChoice":false,"phonetic":"bǎ","translation":"一把","recognition":true,"sourceSection":"比尾巴"},{"word":"伞","phonetic":"sǎn","exampleWord":"雨伞","exampleSentence":"下雨时，我撑起雨伞。","image":"hanzi-preschool/umbrella","translation":"雨伞","recognition":true,"sourceSection":"比尾巴","imageChoice":true}]}',2,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 3（兔最公喝）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"兔","phonetic":"tù","exampleWord":"小兔","exampleSentence":"小兔跳到树下。","image":"hanzi-preschool/rabbit","translation":"小兔","recognition":true,"sourceSection":"比尾巴","imageChoice":true},{"word":"最","exampleWord":"最短","exampleSentence":"这两条绳子中，哪条最短？","image":"hanzi-preschool/short-rope","imageChoice":false,"phonetic":"zuì","translation":"最短","recognition":true,"sourceSection":"比尾巴"},{"word":"公","exampleWord":"公鸡","exampleSentence":"公鸡站在草地上。","image":"chinese-pinyin/rooster-crowing","imageChoice":false,"phonetic":"gōng","translation":"公鸡","recognition":true,"sourceSection":"比尾巴"},{"word":"喝","phonetic":"hē","exampleWord":"喝水","exampleSentence":"运动后，我要喝水。","image":"chinese-pinyin/drinking-water","translation":"喝水","recognition":true,"sourceSection":"乌鸦喝水","imageChoice":true}]}',3,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 4（只处找许）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"只","exampleWord":"一只","exampleSentence":"草地上有一只小兔。","image":"hanzi-preschool/rabbit","imageChoice":false,"phonetic":"zhī","translation":"一只","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"处","exampleWord":"到处","exampleSentence":"森林里到处都是树。","image":"hanzi-preschool/forest","imageChoice":false,"phonetic":"chù","translation":"到处","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"找","exampleWord":"找到","exampleSentence":"我找到盒子里的球了。","image":"hanzi-preschool/inside-box","imageChoice":false,"phonetic":"zhǎo","translation":"找到","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"许","exampleWord":"许多","exampleSentence":"许多树站在森林里。","image":"hanzi-preschool/forest","imageChoice":false,"phonetic":"xǔ","translation":"许多","recognition":true,"sourceSection":"乌鸦喝水"}]}',4,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 5（石出法放）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"石","phonetic":"shí","exampleWord":"石头","exampleSentence":"路边有一块石头。","image":"hanzi-preschool/stone","translation":"石头","recognition":true,"sourceSection":"乌鸦喝水","imageChoice":true},{"word":"出","exampleWord":"出来","exampleSentence":"小鸟飞出来了。","image":"hanzi-preschool/flying-bird","imageChoice":false,"phonetic":"chū","translation":"出来","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"法","exampleWord":"办法","exampleSentence":"我用搭积木的办法做了一座桥。","image":"chinese-pinyin/building-blocks","imageChoice":false,"phonetic":"fǎ","translation":"办法","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"放","exampleWord":"放好","exampleSentence":"我把图书放好了。","image":"hanzi-preschool/book","imageChoice":false,"phonetic":"fàng","translation":"放好","recognition":true,"sourceSection":"乌鸦喝水"}]}',5,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 6（进高点彩）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"进","exampleWord":"进去","exampleSentence":"我把球放进去。","image":"hanzi-preschool/inside-box","imageChoice":false,"phonetic":"jìn","translation":"进去","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"高","exampleWord":"高高","exampleSentence":"高高的树上有叶子。","image":"hanzi-pilot/hanzi-shu","imageChoice":false,"phonetic":"gāo","translation":"高高","recognition":true,"sourceSection":"乌鸦喝水"},{"word":"点","exampleWord":"雨点","exampleSentence":"雨点从云里落下来。","image":"hanzi-pilot/hanzi-yu","imageChoice":false,"phonetic":"diǎn","translation":"雨点","recognition":true,"sourceSection":"雨点儿"},{"word":"彩","exampleWord":"彩色","exampleSentence":"盘子里有彩色的纸。","image":"hanzi-preschool/color-paper","imageChoice":false,"phonetic":"cǎi","translation":"彩色","recognition":true,"sourceSection":"雨点儿"}]}',6,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 7（半空问回）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"半","exampleWord":"一半","exampleSentence":"苹果切成了两半。","image":"hanzi-preschool/half-apple","imageChoice":false,"phonetic":"bàn","translation":"一半","recognition":true,"sourceSection":"雨点儿"},{"word":"空","exampleWord":"天空","exampleSentence":"天空里有一朵白云。","image":"hanzi-pilot/hanzi-yun","imageChoice":false,"phonetic":"kōng","translation":"天空","recognition":true,"sourceSection":"雨点儿"},{"word":"问","exampleWord":"提问","exampleSentence":"小朋友向老师提问。","image":"english-career/teacher","imageChoice":false,"phonetic":"wèn","translation":"提问","recognition":true,"sourceSection":"雨点儿"},{"word":"回","exampleWord":"回家","exampleSentence":"我和家人一起回家。","image":"english-family/family","imageChoice":false,"phonetic":"huí","translation":"回家","recognition":true,"sourceSection":"雨点儿"}]}',7,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 8（答方久更）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"答","exampleWord":"回答","exampleSentence":"小朋友回答老师的问题。","image":"english-career/teacher","imageChoice":false,"phonetic":"dá","translation":"回答","recognition":true,"sourceSection":"雨点儿"},{"word":"方","exampleWord":"方形","exampleSentence":"一张方形白纸摆在桌上。","image":"hanzi-preschool/square-paper","imageChoice":false,"phonetic":"fāng","translation":"方形","recognition":true,"sourceSection":"雨点儿"},{"word":"久","exampleWord":"很久","exampleSentence":"这棵树已经长了很久。","image":"hanzi-pilot/hanzi-shu","imageChoice":false,"phonetic":"jiǔ","translation":"很久","recognition":true,"sourceSection":"雨点儿"},{"word":"更","exampleWord":"更长","exampleSentence":"这条绳子比另一条更长。","image":"hanzi-preschool/long-rope","imageChoice":false,"phonetic":"gèng","translation":"更长","recognition":true,"sourceSection":"雨点儿"}]}',8,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 9（牛羊爪元）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"牛","phonetic":"niú","exampleWord":"小牛","exampleSentence":"小牛低头吃草。","image":"english-animal/cow","translation":"小牛","recognition":true,"sourceSection":"语文园地八","imageChoice":true},{"word":"羊","phonetic":"yáng","exampleWord":"小羊","exampleSentence":"小羊有软软的毛。","image":"english-animal/sheep","translation":"小羊","recognition":true,"sourceSection":"语文园地八","imageChoice":true},{"word":"爪","exampleWord":"爪子","exampleSentence":"小猫伸出一只爪子。","image":"hanzi-preschool/cat-paw","imageChoice":true,"phonetic":"zhuǎ","translation":"爪子","recognition":true,"sourceSection":"语文园地八"},{"word":"元","exampleWord":"一元","exampleSentence":"这是一枚一元硬币。","image":"hanzi-preschool/one-yuan","imageChoice":true,"phonetic":"yuán","translation":"一元","recognition":true,"sourceSection":"语文园地八"}]}',9,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';

INSERT INTO lesson (unit_id,name,type,content,sort_order,star_reward) SELECT id,'阅读三 · 10（拼音）','WORD','{"type":"WORD","textbook":"人教版统编语文一年级上册（2024年修订版）","textbookUnit":8,"items":[{"word":"拼","exampleWord":"拼图","exampleSentence":"我把拼图拼好了。","image":"hanzi-preschool/puzzle","imageChoice":true,"phonetic":"pīn","translation":"拼图","recognition":true,"sourceSection":"语文园地八"},{"word":"音","exampleWord":"声音","exampleSentence":"我们听老师的声音。","image":"english-career/teacher","imageChoice":false,"phonetic":"yīn","translation":"声音","recognition":true,"sourceSection":"语文园地八"}]}',10,3 FROM unit WHERE theme_id=10 AND name='2024一年级上·阅读三';
